ClubWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url,include
from django.contrib.auth import logout
from django.conf import settings
from .views import meeting_alert,myproject_editview,myproject_deleteview,myprojects_view,dp_APIview,ProjectHostAPIView,change_password,contactus,project_list_view,add_project,eventfeedbacksView,FeedbackAPIView,edit_event,getevent_apiview,eventregistrationsView,editmemberprofileview,member_list_view,RegistrationAPIView,memberprofileview,nearestEventsAPIView,EventlistAPIView,getprofile_apiview,editprofileview,home,register,create_event,login_view,event_list_view,event_detailview,logout_user

urlpatterns = [
    url(r'^$',home,name='home'),
    url(r'^member/(?P<username>[\w\-]+)/',memberprofileview,name="member-detail"),
    url(r'^api/events/$',EventlistAPIView.as_view(),name="get-eventslist"),
    url(r'^api/event/feedback/$',FeedbackAPIView.as_view(),name='event-feedback'),
    url(r'^api/event/register/$',RegistrationAPIView.as_view(),name='event-register'),
    url(r'^api/nearevents/$',nearestEventsAPIView.as_view(),name="get-nearevents"),
    url(r'^home/$',register,name="index"),
    url(r'^password/$',change_password, name='change_password'),
    url(r'^members/$',member_list_view,name="members-list"),
    url(r'^projects/$',project_list_view,name="project-list"),
    url(r'^add_project/$',add_project,name="add_project"),
    url(r'^create_event/$',create_event,name="add_event"),
    url(r'^login/$',login_view,name="login_view"),
    url(r'^events/$',event_list_view,name="events-list"),
    url(r'^profile/$',editprofileview,name="profile"),
    url(r'^event/(?P<pk>(\d+)+)/feedbacks/$',eventfeedbacksView,name="event-feedbacks"),
    url(r'^event/(?P<pk>(\d+)+)/registrations/$',eventregistrationsView,name="event_registration"),
    url(r'^api/getevent/$',getevent_apiview.as_view(),name="get-eventdetail"),
    url(r'^api/hosts/$',ProjectHostAPIView.as_view(),name="get-projecthosts"),
    url(r'^api/UpdateProfilePicture/$',dp_APIview.as_view(),name="post-dp"),
    url(r'^api/getprofile/$',getprofile_apiview.as_view(),name="get-userprofile"),
    # url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'), #removed when updated to django==3
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^event/detail/(?P<pk>(\d+)+)/$',event_detailview,name="detailview-event"),
    url(r'^update_event/$',edit_event,name="update_event"),
    url(r'^update_member/$',editmemberprofileview,name="update_member"),
    url(r'^myprojects/$',myprojects_view,name="myprojects"),
    url(r'^contactus/$',contactus,name='contactus'),
    url(r'^send_notifications/$', meeting_alert,name="send-meeting_alert"),
    url(r'^projects/edit/(?P<pk>(\d+)+)/$',myproject_editview,name="edit-project"),
    url(r'^projects/delete/(?P<pk>(\d+)+)/$',myproject_deleteview,name="delete-project"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)
    fname = models.CharField(max_length=100, blank=True)
    lname = models.CharField(max_length=100, blank=True)
    github = models.CharField(max_length=100, blank=True)
    dp = models.CharField(max_length=1000, blank=True)
    batch = models.IntegerField(default=2017)
    facebook = models.CharField(max_length=100, blank=True)
    linkedin = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    bio = models.TextField(blank=True, null=True)
    label = models.CharField(max_length=100 , blank=True)
    company = models.CharField(max_length=100, blank=True)
    location = models.CharField(max_length=100,blank=True)
    frameworks = models.CharField(max_length=500,blank=True)
    languages = models.CharField(max_length=500,blank=True)
    achivements = models.CharField(max_length=1000,blank=True)
    he_profile = models.CharField(max_length=100,blank=True)
    spoj_profile = models.CharField(max_length=100,blank=True)
    he_ques = models.IntegerField(default=0)
    codechef_profile = models.CharField(max_length=100,blank=True)
    codechef_ques = models.IntegerField(default=0)
    spoj_ques = models.IntegerField(default=0)
    git_repos = models.IntegerField(default=0)
    my_website = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.fname

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Event(models.Model):
    description = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=500)
    host = models.ManyToManyField(User)
    venue = models.CharField(max_length=100)
    fee = models.IntegerField(default=0)
    rules = models.TextField(blank=True, null=True)
    prerequistes = models.TextField(blank=True, null=True)
    start_date = models.DateField(default=datetime.date.today,auto_now=False,auto_now_add=False)
    end_date = models.DateField(default=datetime.date.today,auto_now=False,auto_now_add=False)
    start_time = models.TimeField(default=datetime.datetime.now().time(),auto_now=False,auto_now_add=False)
    end_time = models.TimeField(default=datetime.datetime.now().time(),auto_now=False,auto_now_add=False)
    def __str__(self):
        return self.title 

class registration(models.Model):
    eventid = models.IntegerField()
    mobile = models.CharField(max_length=20)
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100,default="")
    College = models.CharField(max_length=300)
    email = models.EmailField()
    query = models.CharField(max_length=1000,default="")

    def __str__(self):
        return self.fname + str(self.eventid)

class feedback(models.Model):
    eventid = models.IntegerField()
    name = models.CharField(max_length=100,blank=True)
    comment = models.TextField()
    star = models.IntegerField(default=0)

    def __str__(self):
        return str(self.star) +" "+ self.name 

class project(models.Model):
    description = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=500)
    owner = models.ManyToManyField(User)
    demo_link = models.CharField(max_length=100,blank=True)
    source = models.CharField(max_length=100)
    technologies = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render,redirect,get_object_or_404

from ClubWebsite import settings
from .models import Profile,Event,registration,feedback,project
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.utils import timezone
import datetime
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .serializers import projecthostSerializer,feedbackSerializer,Event1Serializer,profileSerializer,EventSerializer,registrationSerializer,UserSerializer
from rest_framework.generics import RetrieveAPIView,ListAPIView,CreateAPIView
import requests
import json

# Create your views here.
class RegistrationAPIView(CreateAPIView):
    queryset = registration.objects.all()
    serializer_class = registrationSerializer

class FeedbackAPIView(CreateAPIView):
    queryset = feedback.objects.all()
    serializer_class = feedbackSerializer

@login_required
def eventregistrationsView(request,pk):
    event=get_object_or_404(Event,pk=pk)
    if not request.user.is_superuser and request.user not in event.host.all():
        return redirect('/profile/')
    obj = registration.objects.filter(eventid=pk)
    return render(request,'eventregistrations.html',{'obj':obj,'event':event})

@login_required
def eventfeedbacksView(request,pk):
    event=get_object_or_404(Event,pk=pk)
    if not request.user.is_superuser and request.user not in event.host.all():
        return redirect('/profile/')
    obj = feedback.objects.filter(eventid=pk)
    return render(request,'eventfeedbacks.html',{'obj':obj,'event':event})

def home(request):

    return render(request,'index.html',{})


def contactus(request):

    return render(request,'contactus.html',{})

class ProjectHostAPIView(ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class EventlistAPIView(ListAPIView):
    queryset = Event.objects.order_by('start_date','start_time')
    serializer_class = EventSerializer

class nearestEventsAPIView(ListAPIView):
    serializer_class = EventSerializer

    def get_queryset(self):
        obj = Event.objects.order_by('start_date','start_time')
        past = []
        future = []
        for x in obj :
            if x.end_date <datetime.date.today():
                past.append(x)
            elif x.end_date ==datetime.date.today() and x.end_time < datetime.datetime.now().time():
                past.append(x)
            else :
                future.append(x)
        future.sort(key = lambda x: (x.start_date , x.start_time))
        return future[:3]


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if username and password:
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                redirect('/profile/')
            else:
                return render(request,'login.html',{'err':'Incorrect Username/Password!!'})
        else:
            return render(request,'login.html',{'err':'Enter Username/Password correctly!!'})
    elif request.method == 'GET':
        if request.user.is_authenticated :
            if request.user.is_superuser :
                return redirect('/home/')
            return redirect('/profile/')
        return render(request,'login.html',{})
    return redirect('/profile/')

@login_required
def logout_user(request):	#added when updated to django==3
    logout(request)
    return redirect(settings.LOGOUT_URL)

@login_required
def register(request):
    if not request.user.is_superuser:
        return redirect('/profile/')
    elif request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        email = request.POST.get('email', None)
        batch = request.POST.get('batch', None)
        user, created = User.objects.get_or_create(username=username, email=email)
        if created:
            user.set_password(password)
            user.save()
            url = 'http://2factor.in/API/V1/053efa22-e848-11e6-afa5-00163ef91450/ADDON_SERVICES/SEND/TSMS'
            data = {'From': 'MANNAN','To':username,'TemplateName':'MANAN-welcome','VAR1':email,'VAR2':username,'VAR3':password}
            headers = {'Content-Type': 'application/json'}
            r = requests.post(url, data=json.dumps(data), headers=headers)
            user.profile.batch = batch
            user.profile.save()
            return render(request,'addMember.html',{'msg':"success"})
        else :
            return render(request,'addMember.html',{'err':"User already Exist!!"})
    else:
        return render(request,'addMember.html',{})


@login_required
def create_event(request):
    obj1 = User.objects.all()
    obj=[]
    for x in obj1:
        obj.append({'mobile':x.username,'name':x.profile.fname +" "+ x.profile.lname })
    obj = json.dumps(obj)
    if not request.user.is_superuser:
            return redirect('/profile/')
    elif request.method == 'POST':
        title = request.POST.get('title', None)
        description = request.POST.get('description', None)
        rules = request.POST.get('rules', None)
        prerequistes = request.POST.get('prerequistes', None)
        fee = request.POST.get('fee', None)
        venue = request.POST.get('venue', None)
        start_time = request.POST.get('start_time', None)
        end_time = request.POST.get('end_time', None)
        start_date = request.POST.get('start_date', None)
        end_date = request.POST.get('end_date', None)
        host = request.POST.get('host', None)
        event = Event.objects.create(title=title,end_date=end_date,start_date=start_date,end_time=end_time,start_time=start_time,description=description,rules=rules,prerequistes=prerequistes,venue=venue,fee=fee)
        event.save()
        a=host.split()
        for x in a:
            try:
                user=User.objects.get(username=x)
                event.host.add(user)
            except User.DoesNotExist:
                pass
        event.save()
        return render(request,'addEvent.html',{'msg':"success",'obj':obj})
    elif request.method == 'GET':
        return render(request,'addEvent.html',{'obj':obj})

def member_list_view(request):
    obj = User.objects.all()
    m1=0
    m2=10000
    for x in obj:
        if x.profile.batch>m1:
            m1=x.profile.batch
        if x.profile.batch<m2:
            m2=x.profile.batch
    print(m1,m2)
    member = []
    for x in range(m1,m2-1,-1):
        member.append({'batch':x,'users':[]})

    print(member)
    print("-----")
    for x in obj:
        member[m1-x.profile.batch]['users'].append(x)
    print(member)
    print("-----")
    return render(request,'members.html',{'member':member})


def project_list_view(request):
    obj = project.objects.all()
    return render(request,'projects.html',{'obj':obj})

def event_list_view(request):
    obj = Event.objects.order_by('start_date','start_time')
    past = []
    future = []
    live = []
    for x in obj :
        if x.end_date <datetime.date.today():
            past.append(x)
        elif x.end_date ==datetime.date.today() and x.end_time < datetime.datetime.now().time():
            past.append(x)
        elif x.start_date > datetime.date.today() or (x.start_date == datetime.date.today() and x.start_time > datetime.datetime.now().time()):
            future.append(x)
        else :
            live.append(x)
    past =past[::-1]
    return render(request,'events.html',{'past':past,'future':future,'live':live})

def event_detailview(request,pk):
    obj = get_object_or_404(Event,pk=pk)
    past =0
    counts = registration.objects.filter(eventid=obj.id).count()
    IsHost = True if request.user.is_superuser or request.user in obj.host.all() else False
    if obj.end_date < datetime.date.today() or (obj.end_date == datetime.date.today() and obj.end_time <datetime.datetime.now().time() ) :
        past=1
    return render(request,'eventDetails.html',{'obj':obj,'past':past,'counts':counts,'host':IsHost})

@login_required
def editprofileview(request):
    if request.method == 'POST':
        username = request.POST.get('mobile', None)
        email = request.POST.get('email', None)
        fname = request.POST.get('fname', None)
        lname = request.POST.get('lname', None)
        github = request.POST.get('github', None)
        facebook = request.POST.get('facebook', None)
        linkedin = request.POST.get('linkedin', None)
        twitter = request.POST.get('twitter', None)
        frameworks = request.POST.get('frameworks', None)
        bio = request.POST.get('bio', None)
        location = request.POST.get('location', None)
        achivements = request.POST.get('achivements', None)
        company = request.POST.get('company', None)
        languages = request.POST.get('languages', None)
        he_profile = request.POST.get('he_profile', None)
        codechef_profile = request.POST.get('codechef_profile', None)
        spoj_profile = request.POST.get('spoj_profile', None)
        my_website = request.POST.get('my_website', None)

        try:
            user=User.objects.get(username=username)
        except User.DoesNotExist :
            return render(request,'myprofile.html',{'err':"user does not exist!!"})
        user.profile.email = email
        user.profile.fname = fname
        user.profile.lname = lname
        user.profile.github = github
        user.profile.facebook = facebook
        user.profile.twitter = twitter
        user.profile.linkedin = linkedin

main/templates/Memberdetail.html
{% extends "header.html" %}

{% block page_title %}
<title>{{member.profile.fname}} {{member.profile.lname}} | Member | Manan | Programing Club Of YMCA University, Faridabad</title>

{% endblock page_title %}

{% block page_context %}
<br/><br/>

<div class="container">
  <div class="row">
    <div class="col-lg-3">
     {% if member.profile.dp %}
     <img src="{{member.profile.dp}}" class="img-thumbnail" width="200px" height="200px"/> 
     {% else %}
     <img data-name="{{member.profile.fname}}"  data-char-count="2" class="profile img-thumbnail" width="200px" height="200px" id="user-display-image"/> 
     {% endif %}
   </div>
   <div class="col-lg-6">
    <h2 class="txxt-body">{{member.profile.fname}} {{member.profile.lname}}</h2>
    <span class="badge badge-secondary">{{member.profile.label}}</span>
    <p>
      <small class="text-muted">
        {% if member.profile.company %}<i class="fa fa-briefcase"></i>&nbsp;{{member.profile.company}}<br/>{% endif %}
        <i class="fa fa-graduation-cap"></i>&nbsp;{{member.profile.batch}}<br/>
        <i class="fa fa-phone"></i>&nbsp;&nbsp;+91-{{member.username}}<br/>
        <i class="fa fa-envelope"></i>&nbsp;&nbsp;{{member.email}}
      </small>
    </p>
  </div>
  <div class="col-lg-3">
    <small class="text-muted">
      <p>Bio</p>
      <hr>
    </small>
    <p style="line-height: 1.1;font-size:80%">{{member.profile.bio}}</p>
    <small class="text-muted">
      <p>Social Links</p>
      <hr>
      <a href="{{member.profile.my_website}}" target="_new"><i class="fa fa-globe fa-2x"></i></a>&nbsp;
      <a href="https://facebook.com/{{member.profile.facebook}}" target="_new"><i class="fa fa-facebook-official fa-2x"></i></a>&nbsp;
      <a href="mailto:{{member.profile.email}}" target="_new"><i class="fa fa-envelope fa-2x"></i></a>&nbsp;
      <a href="https://github.com/{{member.profile.github}}" target="_new"><i class="fa fa-github fa-2x"></i></a>&nbsp;
      <a href="https://linkedin.com/in/{{member.profile.linkedin}}" target="_new"><i class="fa fa-linkedin fa-2x"></i></a>&nbsp;
      <a href="https://twitter.com/{{member.profile.twitter}}" target="_new"><i class="fa fa-twitter fa-2x"></i></a>&nbsp;
    </small>
  </div>
</div>
<div class="row">
  <div class="col-lg-3"><br/>
    <p class="txxt-head">Profile</p>
    <h3 class="txxt-body">Menu</h3> 
    <ul class="list-group">
      <a href="#Detailed_Profile"><li class="list-group-item">Detailed Profile</li></a>
      <a href="#Competitive_Coding"><li class="list-group-item">Competitive Coding</li></a>
      <a href="#Open_source"><li class="list-group-item">Open source</li></a>
      {% if member.project_set.all %}<a href="#Projects"><li class="list-group-item">Projects</li></a></a>{% endif %}
      {% if ach %}<a href="#Achievements"><li class="list-group-item">Achievements</li></a>{% endif %}
      {% if member.event_set.all %}<a href="#Events_Hosted"><li class="list-group-item">Events Hosted</li></a>{% endif %}
    </ul>
  </div>
  <div class="col-lg-9" style="background-color: #fff">
    <div class="container">
      <small class="text-muted" id="Detailed_Profile">
        <br/><br/><br/>
        <br/>
        <p class="txxt-body">Detailed Profile:</p>
        <hr>
      </small>
      <p class="txxt-head">Languages: {{member.profile.languages}}</p>

      <p class="txxt-head">Frameworks & Libraries: {{member.profile.frameworks}}</p>
    </div>
    <small class="text-muted"  id="Competitive_Coding">
      <br/><br/><br/><br/>
      <p class="txxt-body">Competitive Coding</p>
      <hr>
    </small>
    <p class="txxt-head"><a href="https://www.hackerearth.com/@{{member.profile.he_profile}}">Hackerearth</a>: <span id="he_quest">Loading Data...</span> </p>

    <p class="txxt-head"><a href="https://www.codechef.com/users/{{member.profile.codechef_profile}}">Codechef</a>: <span id="codechef_quest">Loading Data...</span> </p>

    <p class="txxt-head"><a href="http://spoj.com/users/{{member.profile.spoj_profile}}">Spoj</a>: <span id="spoj_quest">Loading Data...</span></p>

    <small class="text-muted" id="Open_source">
      <br/><br/><br/><br/>
      <p class="txxt-body">Open Source</p>
      <hr>
    </small>
    <p class="txxt-head"><a href="https://github.com/{{member.profile.github}}">Github</a><span id="git_repos">: Loading Data...</span></p>

    {% if member.project_set.all %}
    <small class="text-muted" id="Projects">
      <br/><br/><br/><br/>
      <p class="txxt-body">Projects</p>
      <hr>
    </small>
    <div class="row">
      {% for x in member.project_set.all %}

      <div class="col-lg-4" style="margin-top: 10px;">
        <div class="card border-primary">
          <!--<img class="card-img-top" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_15f77c274ec%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_15f77c274ec%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22118.015625%22%20y%3D%2297.2%22%3E318x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image cap">-->
          <div class="card-header">
            {{x.title}}
          </div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">
              {{x.description}}
            </h6>
            <p class="card-text">Technologies used:{{x.technologies}} </p>

          </div>
          <div class="card-footer">
            <a href="{{x.source}}" class="float-right">View Source</a>
            <span class="float-right">&nbsp; | &nbsp;</span> 
            <a href="{{x.demo_link}}" class="float-right">View Demo</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    
    {% if ach %}
    <small class="text-muted" id="Achievements">
      <br/><br/><br/><br/>
      <p class="txxt-body">Achievements</p>
      <hr>
    </small>
    <p>
      <ul>
        {% for x in ach %}
        <li>{{x}}</li>
        {% endfor %}
      </ul>
    </p>
    {% endif %}
    {% if member.event_set.all %}
    <small class="text-muted" id="Events_Hosted">
      <br/>
      <p class="txxt-body">Events Hosted</p>
      <hr>
    </small>
    <p>
      <ul>
        {% for x in member.event_set.all %}
        <a href="/event/detail/{{x.pk}}"><li>{{x.title}}</li></a>
        {% endfor %}
      </ul>
    </p>
    {% endif %}
  </div>
</div>
</div>

<br/><br/>
{% endblock page_context %}
{% block page_scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script >
  !function(e){var t=function(e,t){var a,n=e.charCodeAt(t);return 55296>n||n>56319||e.length<=t+1||(a=e.charCodeAt(t+1),56320>a||a>57343)?e[t]:e.substring(t,t+2)},a=function(e,a,n){for(var i,r="",o=0,c=0,d=e.length;d>o;)i=t(e,o),c>=a&&n>c&&(r+=i),o+=i.length,c+=1;return r};e.fn.initial=function(t){var n,i=["#1abc9c","#16a085","#f1c40f","#f39c12","#2ecc71","#27ae60","#e67e22","#d35400","#3498db","#2980b9","#e74c3c","#c0392b","#9b59b6","#8e44ad","#bdc3c7","#34495e","#2c3e50","#95a5a6","#7f8c8d","#ec87bf","#d870ad","#f69785","#9ba37e","#b49255","#b49255","#a94136"];return this.each(function(){var r=e(this),o=e.extend({name:"Name",color:null,seed:0,charCount:1,textColor:"#ffffff",height:100,width:100,fontSize:60,fontWeight:400,fontFamily:"HelveticaNeue-Light,Helvetica Neue Light,Helvetica Neue,Helvetica, Arial,Lucida Grande, sans-serif",radius:0},t);o=e.extend(o,r.data());var c=a(o.name,0,o.charCount).toUpperCase(),d=e('<text text-anchor="middle"></text>').attr({y:"50%",x:"50%",dy:"0.35em","pointer-events":"auto",fill:o.textColor,"font-family":o.fontFamily}).html(c).css({"font-weight":o.fontWeight,"font-size":o.fontSize+"px"});if(null==o.color){var h=Math.floor((c.charCodeAt(0)+o.seed)%i.length);n=i[h]}else n=o.color;var f=e("<svg></svg>").attr({xmlns:"http://www.w3.org/2000/svg","pointer-events":"none",width:o.width,height:o.height}).css({"background-color":n,width:o.width+"px",height:o.height+"px","border-radius":o.radius+"px","-moz-border-radius":o.radius+"px"});f.append(d);var l=window.btoa(unescape(encodeURIComponent(e("<div>").append(f.clone()).html())));r.attr("src","data:image/svg+xml;base64,"+l)})}}(jQuery);
</script>
<script> $('.profile').initial(); </script>
<script>
  $(document).ready(function(){
    $.ajax({
      type: "GET",
      url: "https://manan-scrappers.herokuapp.com/competitive/spoj/?user={{member.profile.spoj_profile}}",
      success: function(data)
      { 
          //data=JSON.stringify(data);
          console.log(data);
          if(data.error){
            $('#spoj_quest').html("Invalid User"); 
          }else{
            $('#spoj_quest').html(data.problemssolved);
          }
        },
        error: function(data)
        {
          console.log('error'); 
          $('#spoj_quest').html("Failed to load data");      
        }
      });

  })
</script>
<script>
  $(document).ready(function(){
    $.ajax({
      type: "GET",
      url: "https://manan-scrappers.herokuapp.com/competitive/hackerearth/?user={{member.profile.he_profile}}",
      success: function(data)
      { 
          //data=JSON.stringify(data);
          console.log(data);
          if(data.error){
            $('#he_quest').html("Invalid User"); 
          }else{
            $('#he_quest').html(data.problemssolved);
          }
        },
        error: function(data)
        {
          console.log('error');   
          $('#he_quest').html("Failed to load data");    
        }
      });

  })
</script>
<script>
  $(document).ready(function(){
    $.ajax({
      type: "GET",
      url: "https://manan-scrappers.herokuapp.com/competitive/codechef/?user={{member.profile.codechef_profile}}",
      success: function(data)
      { 
          //data=JSON.stringify(data);
          console.log(data);
          if(data.error){
            $('#codechef_quest').html("Invalid User"); 
          }else{
            $('#codechef_quest').html(data.problemssolved);
          }
        },
        error: function(data)
        {
          console.log('error'); 
          
          $('#codechef_quest').html("Failed to load data"); 
          
        }
      });

  })
</script>
<script>
  $(document).ready(function(){
    $.ajax({
      type: "GET",
      url: "https://api.github.com/users/{{member.profile.github}}",
      success: function(data)
      { 
          //data=JSON.stringify(data);
          console.log(data);
          $('#git_repos').html('<br/><span class="txxt-body">Repositories: </span>'+data.public_repos);
        },
        error: function(data)
        {
          console.log('error');  
          $('#git_repos').html("Failed to load data");    
        }
      });

  })
</script>
{% endblock page_scripts %}